csv_column_defs = list(version_numbers = c("v0.0.0.9000", "vTEST"),
                       cage = list("v0.0.0.9000" = list(start = readr::col_datetime(format = ""),
                                                           start.date.local = readr::col_date(format = ""),
                                                           start.time.local = readr::col_time(format = ""),
                                                           study.code = readr::col_character(),
                                                           aggregation.seconds = readr::col_double(),
                                                           group.name = readr::col_character(),
                                                           cage.name = readr::col_character(),
                                                           animals.cage.quantity = readr::col_integer(),
                                                           light.cycle = readr::col_character(),
                                                           movement.mean.per_cage.cm_s.hour = readr::col_double(),
                                                           wheel_occupancy.mean.per_cage.s.hour = readr::col_double(),
                                                           food_occupancy.mean.per_cage.s.hour = readr::col_double(),
                                                           water_occupancy.mean.per_cage.s.hour = readr::col_double())),
                          animal = list("v0.0.0.9000" = list(start = readr::col_datetime(format = ""),
                                                             start.date.local = readr::col_date(format = ""),
                                                             start.time.local = readr::col_time(format = ""),
                                                             study.code = readr::col_character(),
                                                             aggregation.seconds = readr::col_double(),
                                                             group.name = readr::col_character(),
                                                             cage.name = readr::col_character(),
                                                             animals.cage.quantity = readr::col_integer(),
                                                             light.cycle = readr::col_character(),
                                                             animal.id = readr::col_character(),
                                                             strain = readr::col_character(),
                                                             sex = readr::col_character(),
                                                             genotype = readr::col_character(),
                                                             birth.date = readr::col_date(format = ""),
                                                             movement.animal.cm_s.hour = readr::col_double(),
                                                             wheel_occupancy.animal.s.hour = readr::col_double(),
                                                             food_occupancy.animal.s.hour = readr::col_double(),
                                                             water_occupancy.animal.s.hour = readr::col_double())),
                          annotation = list("v0.0.0.9000" = list(ID = readr::col_double(),
                                                                 created = readr::col_datetime(format = ""),
                                                                 created_date.local = readr::col_date(format = ""),
                                                                 created_time.local = readr::col_time(format = ""),
                                                                 pin_start_date.local = readr::col_date(format = ""),
                                                                 pin_start_time.local = readr::col_time(format = ""),
                                                                 pin_end_date.local = readr::col_date(format = ""),
                                                                 pin_end_time.local = readr::col_time(format = ""),
                                                                 study_code = readr::col_character(),
                                                                 group_name = readr::col_character(),
                                                                 cage_name = readr::col_character(),
                                                                 creator = readr::col_character(),
                                                                 contents = readr::col_character(),
                                                                 reply_to = readr::col_character(),
                                                                 hashtags = readr::col_character())))

csv_column_defs[["cage"]][["vTEST"]] = csv_column_defs[["cage"]][["v0.0.0.9000"]]
csv_column_defs[["animal"]][["vTEST"]] = csv_column_defs[["animal"]][["v0.0.0.9000"]]
csv_column_defs[["annotation"]][["vTEST"]] = csv_column_defs[["annotation"]][["v0.0.0.9000"]]

usethis::use_data(csv_column_defs, internal = FALSE, overwrite = TRUE)
