#' A Function to Read JAX Envision® activity CSVs
#'
#' This function allows you to read activity CSVs generated by the JAX Envision® software.
#' @param csv File path for the Envision® CSV.
#' @param metadata a metadata object returned by `envision_metadata()`
#' @param tzone Time zone for the study. If left as \code{NULL}, the function will attempt to assume a time zone and throw a warning.
#' @param metrics Should the function expect cage (\code{"cage"}) or animal
#'  (\code{"animal"}) level activity metrics? Default: \code{NULL} tries to
#'  identify whether the csv is animal or cage level.
#' @returns A \code{tibble} with experimental data optimally formatted for downstream analysis.
#' @keywords Envision
#' @export
#' @examples
#' # Writing test cage-level CSV file for an example
#' activity_cage_csv <- tempfile("testactivity", fileext = ".csv")
#' readr::write_lines(activity_cage_csv_example, file = activity_cage_csv)
#'
#' # Reading in test cage-level activity CSV file
#' activity_cage <- read_activity_csv(csv = activity_cage_csv, tz = "US/Pacific")
#'
#' # Glimpsing test activity CSV file
#' dplyr::glimpse(activity_cage_csv)
#'
#' # Removing the activity file
#' file.remove(activity_cage_csv)
#'
#' #' Writing test animal-level CSV file for an example
#' activity_animal_csv <- tempfile("testactivity", fileext = ".csv")
#' readr::write_lines(activity_animal_csv_example, file = activity_animal_csv)
#'
#' # Reading in test animal-level activity CSV file
#' activity_animal <- read_activity_csv(csv = activity_animal_csv, tz = "US/Pacific")
#'
#' # Glimpsing test activity CSV file
#' dplyr::glimpse(activity_animal)
#'
#' # Removing the activity file
#' file.remove(activity_animal_csv)
read_activity_csv <- function(csv, metadata = NULL,
                              tzone = NULL, metrics = NULL) {
  # Ensuring required packages are loaded
  stopifnot(requireNamespace("readr", quietly = TRUE))
  stopifnot(requireNamespace("janitor", quietly = TRUE))
  stopifnot(requireNamespace("dplyr", quietly = TRUE))
  stopifnot(requireNamespace("tibble", quietly = TRUE))

  if (!is.null(metadata)) {
    # Running some checks on the metadata
    stopifnot(is.list(metadata))

    if (!is.na(metadata[["tzone"]])) {
      stopifnot(is.character(metadata[["tzone"]]))
      stopifnot(metadata[["tzone"]] %in% timezones_df$tz_name)
    }

    if (!is.null(metadata[["activity_suite_version"]]) & !is.na(metadata[["activity_suite_version"]])) {
      stopifnot(is.character(metadata[["activity_suite_version"]]))
      activity_csv_version <- metadata[["activity_suite_version"]]
    } else {
      activity_csv_version <- NULL
    }

    if (is.null(tzone) & !is.na(metadata[["tzone"]])) {
      tzone <- metadata[["tzone"]]
    } else if (!is.null(tzone) & !is.na(metadata[["tzone"]])) {
      warning(
        "time zone info provided in both metadata and arguments, ",
        "assuming the argument passed to tzone is the time zone"
      )
    }
  }

  activity_tibble <- read_activity_csv_raw(
    csv,
    tzone,
    metrics,
    activity_csv_version
  )
  return(activity_tibble)
}

#' Low-level internal read_activity_csv
#' @param csv File path for the Envision® CSV.
#' @param tzone Time zone for the study. If left as \code{NULL}, the function will attempt to assume a time zone and throw a warning.
#' @param metrics Should the function expect cage (\code{"cage"}) or animal
#' @noRd
read_activity_csv_raw <- function(csv,
                                  tzone = NULL,
                                  metrics = NULL,
                                  activity_csv_version = NULL) {
  # Ensuring required packages are loaded
  stopifnot(requireNamespace("readr", quietly = TRUE))
  stopifnot(requireNamespace("janitor", quietly = TRUE))
  stopifnot(requireNamespace("dplyr", quietly = TRUE))
  stopifnot(requireNamespace("tibble", quietly = TRUE))

  # Doing variable bindings
  start_date_local <- start_time_local <- startlocal_utc <-
    start <- utc_offset_h <- min_starttime <- assume <- min_starttime_utc <-
    tz_name <- is_dst <- tz_isdst <- group_name <- cage_name <- NULL

  # Looking for a version of the activity CSV
  if (grepl("\\.zip$", csv)) {
    first10_csv <- base::readLines(unzip(csv), n = 10)
  } else {
    first10_csv <- base::readLines(csv, n = 10)
  }
  # Looking at starting comment characters within the first 10 lines of the CSV
  # NOTE: this is to ensure that the comment character can be read in the body
  # of the sheet.
  comment_char_csv <- grep("^#", first10_csv, value = TRUE)
  header_col_csv <- grep("^start,", first10_csv, value = TRUE)
  colnames_csv <- unlist(strsplit(header_col_csv, ","))
  movement_col <- grep("^movement|activity\\.", colnames_csv, value = TRUE)

  if (is.null(activity_csv_version)) {
    activity_csv_version <- "v1.1.0"
  }


  if (is.null(metrics)) {
    metrics <- tolower(gsub(
      "^movement|activity\\.(.*)\\.cm_s\\..*$",
      "\\1",
      movement_col
    ))
    if (grepl("animal", metrics)) {
      metrics <- "animal"
    } else if (grepl("cage", metrics)) {
      metrics <- "cage"
    } else {
      metrics <- "animal"
      warning(paste(
        "Assuming animal metrics, set explicity if otherwise."
      ))
    }
  }

  timespan <- tolower(gsub(
    "^.*\\.cm_s\\.(.*)$",
    "\\1",
    movement_col
  ))

  # Getting definitions of columns by version
  metrics <- tolower(metrics)
  if (metrics %in% c("cage", "animal")) {
    if (activity_csv_version %in% envisionR::csv_column_defs$version_numbers) {
      # Conserving old behavior where column definitions were defined in csv_column_defs
      metrics <- paste0(metrics, "_activity_", timespan)
      activity_cols_def <- envisionR::csv_column_defs[[metrics]][[activity_csv_version]]

      metric_cols <- names(envisionR::csv_column_defs[[metrics]][[activity_csv_version]])
      metric_cols <- metric_cols[(grep("movement", metric_cols):length(metric_cols))]
    } else {
      # Getting the invariant columns from the v0.0.0.9000 version
      metrics_name <- paste0(metrics, "_activity_", timespan)
      activity_cols_def <- envisionR::csv_column_defs[[metrics_name]][["v0.0.0.9000"]]
      movement_col <- grep("movement", names(activity_cols_def), value = TRUE)
      movement_col <- which(names(activity_cols_def) == movement_col)
      activity_cols_prefices <- names(activity_cols_def)[1:(movement_col - 1)]
      activity_cols_def <- activity_cols_def[activity_cols_prefices]

      # Getting the metric columns and coercing them all to double precision
      activity_cols_from_coldefs <- grep(
        paste0(
          metrics, "\\..*\\.",
          timespan, "$"
        ),
        colnames_csv,
        value = TRUE
      )
      for (coldef in activity_cols_from_coldefs) {
        activity_cols_def[[coldef]] <- readr::col_double()
      }
      metric_cols <- activity_cols_from_coldefs
    }
  } else {
    stop("metrics should be defined as either cage or animal level")
  }

  # Reading in raw data
  activity_data <- readr::read_csv(csv,
    skip = length(comment_char_csv),
    col_types = activity_cols_def,
    show_col_types = FALSE
  ) |>
    janitor::clean_names() |>
    tibble::as_tibble()

  # Starting by listing compatible time zones
  compatible_tzones <- activity_data |>
    dplyr::mutate(utc_offset_h = get_utc_offset(
      as.POSIXct(paste(
        start_date_local,
        start_time_local
      )),
      start,
      as_numeric = TRUE
    )) |>
    dplyr::group_by(utc_offset_h) |>
    dplyr::mutate(min_starttime = min(start)) |>
    dplyr::select(utc_offset_h, min_starttime) |>
    dplyr::summarize(min_starttime_utc = min(min_starttime)) |>
    dplyr::left_join(timezones_df, by = "utc_offset_h")

  # Assigning time zone
  if (is.null(tzone)) {
    # Attempting to automagically impute an assumed time zone if tz is NULL
    # Identifying all unique UTC offsets in the dataset
    # Then finding compatible assumed time zones
    probable_tzones <- compatible_tzones |>
      dplyr::filter(assume == 1) |>
      dplyr::ungroup() |>
      dplyr::mutate(tz_isdst = FALSE) |>
      as.data.frame()

    for (i in seq_len(nrow(probable_tzones))) {
      probable_tzones[i, "tz_isdst"] <- as.POSIXlt(
        probable_tzones[i, "min_starttime_utc"],
        probable_tzones[i, "tz_name"]
      )$isdst == 1
    }

    probable_tzones <- probable_tzones |>
      dplyr::filter(is_dst == tz_isdst)

    # Getting unique time zones that are assumed.
    unique_tzs <- probable_tzones |>
      dplyr::pull(tz_name) |>
      unique()

    # Setting time zone according to a series of conditions
    if (length(unique_tzs) == 1) {
      tz_assume <- unique_tzs
    } else {
      stop("could not assume a time zone unambiguously.")
    }
    # Throwing a warning if time zone is set as null
    warning(paste0(
      "Assuming time zone: ", tz_assume,
      ". Set time zone explicitly if different."
    ))
  } else {
    if (tzone %in% timezones_df$tz_name) {
      tz_assume <- tzone
      if (!(tzone %in% (compatible_tzones |> dplyr::pull(tz_name)))) {
        warning(paste(
          "UTC offset for the", tzone,
          "time zone mismatches suggested time zones."
        ))
      }
    } else {
      stop(paste("time zone", tzone, "is not a system time zone."))
    }
  }
  activity_data <- activity_data |>
    dplyr::mutate(
      start = as.POSIXct(start, tz = tz_assume),
      tzone = tz_assume
    ) |>
    dplyr::arrange(group_name, cage_name, start)

  attr(activity_data, "metrics") <- janitor::make_clean_names(metric_cols)
  return(activity_data)
}
