#' A Function to Read JAX Envision® CSVs
#'
#' This function allows you to read CSVs generated by the JAX Envision® software.
#' @param csv CSV for your JAX Envision® file.
#' @keywords Envision
#' @export
#' @examples
#' read_envision_csv()

read_envision_csv <- function(csv, tz = NULL) {

  return("This is a stub. This will eventually be a wrapper function.")
}
